extends SceneTree

func _init() -> void:
	var session: SessionService = SessionService.new()
	var meta: MetaProfileService = MetaProfileService.new()
	var event_bus: EventBus = EventBus.new()
	session.initialize(meta, event_bus)
	meta.reset_profile(session.content_library)
	assert(session.start_new_run_with_dough(&"sweet_dough"), "A default-unlocked dough should start a run.")
	assert(session.run_state.screen == GameEnums.Screen.ENCOUNTER, "Run should enter the encounter screen.")
	assert(session.run_state.day_number == 1, "Run should begin on day 1.")
	assert(session.cafe_state.active_pastry != null, "Each day should begin with one active pastry.")
	assert(session.cafe_state.active_pastry.dough_id == &"sweet_dough", "Sweet Dough should seed the opening pastry.")
	session._advance_after_encounter_clear()
	assert(session.run_state.screen == GameEnums.Screen.REWARD, "Day 1 should route to reward.")
	assert(session.choose_reward(&"reward_add_chocolate"), "A valid reward should be choosable.")
	assert(session.run_state.screen == GameEnums.Screen.DOUGH_SELECT, "Choosing a reward should route to the next day dough select.")
	assert(session.run_state.pending_day_number == 2, "Reward resolution should prepare day 2.")
	assert(session.start_new_run_with_dough(&"sweet_dough"), "The selected dough should start day 2.")
	assert(session.run_state.day_number == 2, "Choosing the next dough should start day 2.")
	session._advance_after_encounter_clear()
	assert(session.run_state.screen == GameEnums.Screen.RUN_SHOP, "Day 2 should route to run shop.")
	session.continue_after_shop()
	assert(session.run_state.screen == GameEnums.Screen.DOUGH_SELECT, "Leaving the shop should route to day 3 dough select.")
	assert(session.run_state.pending_day_number == 3, "Shop exit should prepare day 3.")
	assert(session.start_new_run_with_dough(&"sweet_dough"), "The selected dough should start day 3.")
	assert(session.run_state.day_number == 3, "Choosing the next dough should start day 3.")
	session._advance_after_encounter_clear()
	assert(session.run_state.screen == GameEnums.Screen.BOSS_INTRO, "Day 3 should route to boss intro.")
	session.start_boss_encounter()
	assert(session.run_state.screen == GameEnums.Screen.DOUGH_SELECT, "Boss intro should route to boss day dough select.")
	assert(session.run_state.pending_day_number == 4, "Boss intro should prepare day 4.")
	assert(session.start_new_run_with_dough(&"sweet_dough"), "The selected dough should start day 4.")
	assert(session.run_state.day_number == 4, "Boss dough selection should launch day 4.")
	session._finish_run(true, "Smoke test clear.")
	assert(session.run_state.screen == GameEnums.Screen.SUMMARY, "Finishing a run should route to summary.")
	quit()
